### PR TITLE
Insert Delete Cells for All Data Entry forms

### LINKED ISSUE #286: Implementation of Delete Cell and Insert Cell Buttons on Data Key Entry Forms in Climsoft V4
The two commands are working very well in Climsoft V3.2 whereby **Delete Cell** shift all the data at once in the cells upward in the previous cells and **Insert Cell** shift all the data at once in the cells downward. This is still very important and need to be implement in climsoft V4  to save time during data key entry process ;
image

### PR DESCRIPTION
**Pull request by Patowhiz**
Fixes #286
@maxwellfundi @smachua  @mhabimana this is ready for review.

In regard to our Skype discussion I have renamed the right clicks menus as shown below

isnert delete

### CODE REVIEW

**Comment by Patowhiz** [comment]
I have implemented this for all the forms though I understand you can't test the synoptic form. I'm sorting the issue of the elements as mention in issue #304

**Comment by smachua** [comment]
Pull request #307 merged

**Comment by smachua** [comment]
#286 reviewed and merged.

**Comment by mhabimana** [comment]
@Patowhiz I have tested and I am happy to confirm that the Insert Cell and Delete Cell functionality are working well on all the forms.Well done!

**Comment by Patowhiz** [comment]
Perfect.

**Pull request merged**
