### PR TITLE
beta2-update-18072018

### PR DESCRIPTION
**Pull request by smachua**
combined codes

### CODE REVIEW

**Comment by isedwards** [comment]
Thanks @smachua & @mhabimana for putting this together. I'll look at fixing the database connection and merging.

**Comment by isedwards** [comment]
@mhabimana and I have both had a few problems getting this to run, it may just because some of the new NuGet packages are missing.

1532066238845blob

I've added #303 for comparision - this was created automatically by the git command line tools and therefore contains all of the commit history for the work that AMI have been doing.

We can compare #303 to this PR to highlight any differences.

**Comment by smachua** [comment]
@isedwards and @mhabimana please review and approve my latest PR so that the conflicts can be resolved. I recommend that all the modifications I have made be allowed. They are supposed to make the New Forms link well with other existing modules.

**Comment by mhabimana** [comment]
@isedwards Above are the conficting files for you review and merging.

**Comment by isedwards** [comment]
This one looks like it would take a long time to unpick (156 files are recorded as modified and 25 conflicting).  I've not dug into it yet to see why there are so many problems.

**Comment by smachua** [comment]
@isedwards and @mhabimana I modified a number of files but I didn't expect there to be so many conflicts. But since beta2 branch is work ok with us probably by accepting all the new changes will help in resolving the conflicts faster.

**Comment by mhabimana** [comment]
I am closing this PR. A new PR will be sent shortly and we are expecting this will reduces potential conflicts.

**Pull request closed without merging**
