### PR TITLE
Data Entry Forms (Hourly Data, Daily2 Data, Monthly Data,  HourlyWind, Synoptic RA1 Data,Synoptic Carribean Data) 

### LINKED ISSUE #498: form_hourlywind - Data Entry Form For Hourly Wind Data

### PR DESCRIPTION
**Pull request by Patowhiz**
Fixes #498 #496 #497 #499 #500 #507 #547 #490 #508 
Also Fixes some of the issues raised in #543

### CODE REVIEW

**Comment by maxwellfundi** [comment]
@Patowhiz from your last commits could you check that all your `ucrHourlyWind `changes are uploaded, i seem to have a few issues with undefined variables. could you check if it inherits from `UcrTableEntry`

**Comment by Patowhiz** [comment]
@maxwellfundi I have fixed the issues raised above. Kindly go through the PR in preparation to merging it. I have tested it with current database. For the add new be keen on the sequncer values, They have to exist for it to work.
[CLIMSOFT database ](https://github.com/opencdms/climsoft-database/tree/master/sql)

**Comment by Patowhiz** [comment]
@maxwellfundi did you go through the PR. @mhabimana  this is now ready to be made as a PR against the master. The next step is to now remove the conflicts

**Comment by mhabimana** [comment]
@Patowhiz - sounds great. If @maxwellfundi has reviewed this a new PR can now be made.

**Comment by maxwellfundi** [comment]
@mhabimana @Patowhiz  I am sorry I have not been able to review this earlier. Have been away in Ethiopia quite busy in the camp. 
I will review this today and revert by COB/ 

Thank you.

**Comment by mhabimana** [comment]
@maxwellfundi :well noted.

**Comment by maxwellfundi** [comment]
@mhabimana @smachua  I have been going through the forms and are working reasonably well. 

 Just one issue here the `mm_04` does not accept null and this needs to change since if it ever happens that the 4th month is missing then it will not accept that. there is an update to the database this might have been addressed. 

I suggest these can now be merged in- We should keep testing still to make sure if any bug is existing then we have it addressed by the time we have a upgrade version. 

@mhabimana all green here!

**Comment by mhabimana** [comment]
@maxwellfundi - sounds great. We agreed in the last Skype that this PR will be merged to Master and not to Dev then to master.

**Comment by mhabimana** [comment]
@Patowhiz @maxwellfundi -If you are happy then we can merge this into master

**Comment by maxwellfundi** [comment]
great, @Patowhiz please do  a PR with these changes to master

**Pull request closed without merging**
