### PR TITLE
Records Loading

### LINKED ISSUE #392: New data entry forms are taking too long to load
We tried opening the new data entry forms after installation of Climsoft and here are some statistics of how the forms performed on their first load.

1. It took 2 minutes to load form daily 2 which had records 4648 records

2. It also took 7 minutes 40 seconds to load form hourly which had 28648 records 

We were using  an i7 with 8GB of memory and a 3,4 GHZ speed.After this slow loading the forms work okay. 

On the consecutive opening of these forms in the same instance, they loaded almost  instantly but every time a new climsoft session is run then it takes the same time to load.   

This time is too much to wait for the form to load and this needs to be addressed to make the forms more efficient in load time.

### PR DESCRIPTION
**Pull request by Patowhiz**
Fixes #392
Continuation of PR #396
@mhabimana @smachua  this is yet to be completed. We are still looking on the issue of Add New with @dannyparsons

### CODE REVIEW

**Comment by Patowhiz** [comment]
@dannyparsons check on this implementation. It allows us sort the records using any columns even multiple columns. If you agree with it we can now discuss which column to use in determining the order in which the records will be loaded.

**Comment by Patowhiz** [comment]
@mhabimana @smachua previously the column used for sorting was `entryDatetime `. Is there a time when records of say 12th were entered before records of say 10th in the database for whatever reason? Because if its so then sorting by `entryDatetime `will still be wrong for the sequencer. If not then we can proceed using this column

**Comment by dannyparsons** [comment]
This looks good. I suggest that first needs to implement the previous behaviour before any possible changes to this are discussed. I think the urgent changes for the new version are now addressed here.

**Comment by Patowhiz** [comment]
Ok. I'll use the `entryDatetime `field.
Please note, the test database has some tables with `EntryDatetime `rather than `entryDatetime`. Others have the same field but with type **VARCHAR** instead of **DATETIME**. I have not seen this problem with the production database. In order to test this PR correctly when using the test database please make sure you correct this problem cause I'm setting it as the sorting column for all the forms.

**Comment by dannyparsons** [comment]
There seems to be a long delay after clicking Add New before you the blank record. I'll look into this with @Patowhiz.

**Comment by dannyparsons** [comment]
The delay on Add New is now resolved and seems to be functioning correctly. All the speed issues appear to be resolved.
@mhabimana This is now ready.

**Comment by maxwellfundi** [comment]
@mhabimana  I have now tested this this morning and it the speed issues have been fully addressed and the delete bug no longer exists.

**Comment by mhabimana** [comment]
@dannyparsons ,@Patowhiz, @maxwellfundi, I have merged this with the master and I am happy now with the speed of loading data entry forms. We are still testing and in case of any issue I will let you know. Many thanks.

**Pull request merged**
