### PR TITLE
Data Entry Forms Selection

### LINKED ISSUE #549: Improve the Data Key Entry Forms Dialog
Currently the data key entry form that contains links to the key entry forms is using data grid control as a means to for the user to access the key entry forms. This form can be improved to use a much better control. This was mentioned as part of the April code sprint.

key entry forms

### PR DESCRIPTION
**Pull request by Patowhiz**
Fixes #549 
@smachua @mhabimana  this is ready for review

It's a good  that this was already a listview, I have added some changes and changed the implementation based on the proposals made last April.

The new design is as shown below. I'm not sure if the terms I've used are helpful enough.

newest

### CODE REVIEW

**Comment by Patowhiz** [comment]
@smachua I have also seen code that tries to alter the data_forms table on load. Was this temporary? I commented it out but I can add it if it's  still needed.

```
Try
           ' Add a record for key entry mode if not exists
            sql = "ALTER TABLE `data_forms` ADD COLUMN `entry_mode` TINYINT(2) NOT NULL DEFAULT '0' AFTER `sequencer`;"
            conn.Open()
           qry = New MySql.Data.MySqlClient.MySqlCommand(sql, conn)
            qry.CommandTimeout = 0
            qry.ExecuteNonQuery()

            conn.Close()
 Catch ex As Exception
            If ex.HResult <> -2147467259 Then 'Existing record
                MsgBox(ex.HResult & " " & ex.Message)
            End If
            conn.Close()
 End Try
```

**Comment by mhabimana** [comment]
@Patowhiz :Thanks for improving on this. Can you please check the formSynoptic_2_ra1, you have edited this and hence it is not opening.

**Comment by mhabimana** [comment]
@Patowhiz :Is it possible to maintain the horizontal rows separating each form as it was before(see below):
- Proposed Data Entry Forms Selection

image

- Existing Data Entry Forms Selection

image

**Comment by Patowhiz** [comment]
yes it's possible

**Comment by Patowhiz** [comment]
@mhabimana I have now added the gridlines

**Comment by isedwards** [comment]
@Patowhiz - your [question above](https://github.com/opencdms/Climsoft/pull/563#issuecomment-527206237) about code that tries to alter the database whilst the software is running has its own issue here: https://github.com/opencdms/Climsoft/issues/304

**Comment by Patowhiz** [comment]
Thank  you @isedwards  I suggest @smachua to help us identify the areas where the forms are altering the database schema. We should have a central way of doing this. There are several recommended ways of altering database schemas during when updating a software or generally updating software .

I'm thinking of 2 issues

1. An issue on the forms that  currently have code which is altering the database schema. I think We need to address that before the next release.

2. An issue issue about how updates that affect database schema should be implemented in future, I think this will help in our next release.

**Pull request merged**
