### PR TITLE
Revert "background upload progress"

### PR DESCRIPTION
**Pull request by maxwellfundi**
Reverts opencdms/Climsoft#315

### CODE REVIEW

**Comment by maxwellfundi** [comment]
@mhabimana I am wanting to revert your merge here on @Patowhiz pull request. Then he can get to do a new pull request.

**Comment by maxwellfundi** [comment]
@mhabimana Please now pull the latest master. Confirm that you are not getting an error anymore. Then @Patowhiz changes will pushed again.

**Comment by mhabimana** [comment]
@Patowhiz  are you still online? @maxwellfundi noted.

**Comment by maxwellfundi** [comment]
@mhabimana  I am online and @Patowhiz  should be too. Am juggling between a number of things but I should be quick to respond.

**Comment by mhabimana** [comment]
@maxwellfundi Thanks,I am cloning the project and will give you the feedback shortly.

**Comment by mhabimana** [comment]
@maxwellfundi : Very good see below:
image
I am waiting the new PR

**Comment by Patowhiz** [comment]
I am online

**Comment by mhabimana** [comment]
@Patowhiz 👍

**Comment by maxwellfundi** [comment]
@mhabimana Great am now getting to carefully get back @Patowhiz changes now. it could take a few minutes. Thanks.

**Comment by mhabimana** [comment]
@maxwellfundi Noted.

**Pull request merged**
