### PR TITLE
Shifting Cells

### LINKED ISSUE #286: Implementation of Delete Cell and Insert Cell Buttons on Data Key Entry Forms in Climsoft V4
The two commands are working very well in Climsoft V3.2 whereby **Delete Cell** shift all the data at once in the cells upward in the previous cells and **Insert Cell** shift all the data at once in the cells downward. This is still very important and need to be implement in climsoft V4  to save time during data key entry process ;
image

### PR DESCRIPTION
**Pull request by Patowhiz**
Fixes #286

### CODE REVIEW

**Comment by maxwellfundi** [comment]
Testing this.

**Comment by Patowhiz** [comment]
@maxwellfundi the code for shifting the cells has been implemented in away that it works consistently on all the forms. Should we have it as class then adapt it to all the forms or should we copy and paste the code to all the forms

**Comment by maxwellfundi** [comment]
@Patowhiz I believe having a class that we can easily reuse is more sensible thing to do. However in the interest of time, we can have whatever is easy to do now then we can change in the future as long as the functionality stays the same.

**Comment by mhabimana** [comment]
@maxwellfundi I agree with you 100%, @Patowhiz : This is working well on the form Daily and can now be extended to other data entry forms.

**Comment by mhabimana** [comment]
@Patowhiz : I just realise that when shifting upward,it is shifting the record up but it is removing as well the the previous record. So if you do this on the first cell you can not see the issue but in the middle of the cells,you will be able to see this issue. Pls check this.

**Comment by Patowhiz** [comment]
I have sorted the issue above in another pull request  #308

**Pull request merged**
