### PR TITLE
Data Entry Forms

### LINKED ISSUE #498: form_hourlywind - Data Entry Form For Hourly Wind Data

### PR DESCRIPTION
**Pull request by Patowhiz**
Fixes #498 #496 #497 #499 #500 #507 #547 #490 #508
Also Fixes some of the issues raised in #543

### CODE REVIEW

**Comment by Patowhiz** [comment]
@mhabimana here is the new PR

**Comment by Patowhiz** [comment]
@maxwellfundi @isedwards  @smachua  there are conflicts. I think we can discuss on how to resolve the conflicts and then start testing and addressing the remaining specific issues

**Comment by mhabimana** [comment]
@Patowhiz -Thanks,this sounds like a good idea, @isedwards can you have a look and advise?

**Comment by isedwards** [comment]
I'll see how many I can resolve and then we can discuss the ones that are left...

**Comment by mhabimana** [comment]
@isedwards - Great,thanks.

**Comment by maxwellfundi** [comment]
@isedwards have had a look here and it appears we might need just to keep all the changes from Dec branch. The master mostly has the old code which mostly was swapped around

**Comment by isedwards** [comment]
@Patowhiz could you take a quick look [at the conflicts](https://github.com/opencdms/Climsoft/pull/551/conflicts) and check that you agree with @maxwellfundi ?

Almost all of the conflicts are within `frmNew*.vb` and `ucr*.vb` files and it does look like Maxwell is correct.

An exception is `frmLogin.vb` where we should keep **both** the code from dev and the code from master...

```
<<<<<<< dev
            'Newly added code
            clsDataConnection.openConnection()
=======
            conn.Close()
>>>>>>> master

```

**Comment by maxwellfundi** [comment]
@isedwards we moved the code from the forms to the controls. I suggest we keep all the changes in the controls which are the changes in dev.

**Comment by Patowhiz** [comment]
Yes I agree. We move all the code to the controls.

**Pull request merged**
