### PR TITLE
Data Entry Upload Functionality

### LINKED ISSUE #420: Error in transferring data from forms to obsinitial
capture
I am encountering such an error message when I upload data from forms to observationinitial

### PR DESCRIPTION
**Pull request by Patowhiz**
Fixes #420
@opencdms/climsoft-developers @mhabimana this is ready for review. 
Please do not merge yet. I would some feedback on the speed, errors feedback etc
@smachua the time taken for the upload is similar to climsoft v3 I think, I tested the previous code though it ended with deadlocks for huge records like 4000 and above.

### CODE REVIEW

**Comment by mhabimana** [comment]
@Patowhiz : Well noted.Let me test this and come back to you

**Comment by mhabimana** [comment]
@Patowhiz This looks good and promising,the only remaining issue on this is the upload speed.
image

**Comment by Patowhiz** [comment]
I've just pushed additional design changes. Will be pushing the final code shortly. @mhabimana could you confirm if the speed is comparable to v3 of climsoft for the same number of records?

**Comment by mhabimana** [comment]
@Patowhiz Yes, the speed is the same like in V4.0. Any chance to improve on this?

**Comment by Patowhiz** [comment]
@mhabimana I have pushed some design changes that will help the user trace the errors raised using the upload form. Could you test it and give feedback on the error messages created. Keep in mind the upload progress form can be enlarged

**Comment by mhabimana** [comment]
@Patowhiz Noted.

**Comment by mhabimana** [comment]
@Patowhiz Below is the test result. I was trying to upload below daily data from Rwanda (4921 records):
image

- Error report:
image

**Comment by Patowhiz** [comment]
@mhabimana those are the errors raised. Follow up on the specific records by using the selectors to navigate to the records.

**Comment by mhabimana** [comment]
@Patowhiz Thanks.

**Pull request merged**
