### PR TITLE
Upload Progress

### PR DESCRIPTION
**Pull request by Patowhiz**
This is ready for review. Fixes issue #312

### CODE REVIEW

**Comment by Patowhiz** [comment]
@smachua in future we could slightly modify `frmDataTransferProgress `to have a progress bar. It's one of the best way to show progress. I did modify it cause its being used by other forms.

@mhabimana what's the typical number of records that will be uploaded in a real world scenario. I mean how huge could the number of records be? I wasn't quite sure whether this particular functionality would be worth executing in a different thread.

**Comment by smachua** [comment]
pull request #313 reviewed and merged

**Comment by Patowhiz** [comment]
@mhabimana @smachua I'm still concerned about the response to the what I have commented above

**Comment by Patowhiz** [comment]
If they are many records, I can quickly,nicely and neatly implement that as a background worker to improve the performance

**Comment by mhabimana** [comment]
@Patowhiz Thanks .This will depends with how big is the Met Service. Some time Met Service contract for a short period a team of people,let say 20 people or more to digitise data (from the paper records or observation books to the data entry forms). I can imagine,if after transferring data the data entry forms are not cleared,the number of records can accumulate in this table and when time to transfer come,you find there is much to transfer,the good of this is that in the observationinitial don't allow duplicate.

**Comment by mhabimana** [comment]
@Patowhiz For sure there will be many record,but I think the most important is to see the progress of data transfer.Having this in the background would be  very good.

**Comment by Patowhiz** [comment]
Let me implement this in a general way such that the background worker is reusable in all other computation intensive tasks. I'll finish this in the next 2 hours

**Comment by mhabimana** [comment]
@Patowhiz Thanks,Noted.

**Comment by smachua** [comment]
@Patowhiz , @maxwellfundi I suggest that you let me and @mhabimana go through the latest merged code and compile all issues so that you can handle them at once. You may therefore halt any commit until we're done probably in a day or 2.

**Comment by Patowhiz** [comment]
@smachua I only have one pending commit, for the upload progress being done in the background as suggested above. I was afraid that the current implementation might keep the user waiting for all the records to finish uploading since its happening on the main thread.

**Comment by Patowhiz** [comment]
Yes

**Comment by Patowhiz** [comment]
@smachua I have now made the commit

**Pull request merged**
