### PR TITLE
Beta2

### PR DESCRIPTION
**Pull request by smachua**
Beta2 branch without conflicts

### CODE REVIEW

**Comment by mhabimana** [comment]
Beta2 was reviewed and approved though it has got a minor error related to multilingual build task which need to be sorted out.
image

**Comment by isedwards** [comment]
I don't see the multilingual app toolkit (MAT) error, possibly because I have the toolkit installed on my machine.  We should remove MAT entirely for now. I can do that before building the new installer.

**Comment by mhabimana** [comment]
@isedwards - How can I remove this? guidance please.

**Comment by isedwards** [comment]
MAT probably disappeared when we updated to Visual Studio 2017 (and would need to be downloaded again from the Tools > Extensions and Updates menu.

Removing it completely would probably require manually editing the `ClimsoftVer4.vbproj` file (which I wouldn't recommend).  For now, the best solution is probably to install the MAT extension, and then make sure that language translation is disabled for the project.  When MAT is installed there is an option:  Tools > Multilingual App Toolkit > Disable selection (you can only choose this option when the Climsoft solution is open)

**Pull request merged**
