### PR TITLE
background upload progress

### PR DESCRIPTION
**Pull request by Patowhiz**
This is now ready for review. Addresses issue #312.

@smachua the new `frmNewComputationProgress` can be used for any cpu intensive task that needs to be executed in a background task. We can improve its look in future, and the code to that is just 7 lines

```
Dim frm As New frmNewComputationProgress
        frm.SetHeader("Uploading " & ucrLinkedNavigation.iMaxRows & " records")
        frm.SetProgressMaximum(ucrLinkedNavigation.iMaxRows)
        frm.ShowResultMessage(True)
        AddHandler frm.backgroundWorker.DoWork, AddressOf DoUpload
        frm.backgroundWorker.RunWorkerAsync()
        frm.Show()
```

@mhabimana @maxwellfundi my surface has a very high resolution this form could look bigger in a normal laptop, @maxwellfundi  could you look at its size and try to style to be similar to the image shown below. (The header can be made bold, and the fonts of the be changed.). Only the design.

progress bar

### CODE REVIEW

**Comment by mhabimana** [comment]
@maxwellfundi There is a conflict which need to be resolved before the merging of this PR:
image

**Comment by maxwellfundi** [comment]
@mhabimana I can see if its a huge conflict. Let me try get it fixed.

**Comment by Patowhiz** [comment]
Probably because of the addition of the new form which has changed the Project Solution?

**Comment by mhabimana** [comment]
@Patowhiz You are right.

**Comment by maxwellfundi** [comment]
@Patowhiz the conflict was because of the form you added, possibly you had not updated from the master and that caused a conflict. I have kept both changes so can be merged.

**Comment by mhabimana** [comment]
@maxwellfundi Thanks.

**Comment by mhabimana** [comment]
@maxwellfund @Patowhiz : Below is the error I am getting when trying to start the project,I am not sure if you are experiencing the same:
image

**Comment by maxwellfundi** [comment]
let me update my branch from master and see if i get an error, will be back to you shortly @mhabimana

**Comment by mhabimana** [comment]
@maxwellfundi : Have you seen the message below:
 error MSB3577: Two output file names resolved to the same output path: "obj\Debug\ClimsoftVer4.form_agro1.resources"

**Comment by maxwellfundi** [comment]
@mhabimana @Patowhiz This has been caused by a tag on the vbproj file being misplaced. Not sure how that happened but its on the commit where master was merged onto the EFchanges. 

I am going to revert this merge, then @Patowhiz  can create a new pull request with his changes

**Comment by mhabimana** [comment]
@maxwellfundi @Patowhiz Noted.

**Comment by mhabimana** [comment]
@maxwellfundi @Patowhiz 🆗

**Pull request merged**
