### PR TITLE
beta2-update-08092018

### PR DESCRIPTION
**Pull request by smachua**
update to fix user privileges on test database and remove a duplicated folder

### CODE REVIEW

**Comment by isedwards** [comment]
When hundreds of files are changed in a single pull request, the GitHub interface isn't able to show all of the changes instead we see messages like:

> The table of contents is too big to display

In cases like this, I'd recommend making a separate pull request that only deletes the 565 extra backup files, and then you can have a second pull request with you most recent changes so that it is easy to see what has changed.

Most of the changes in this pull request look the same as the changes that were merged a few days ago in two pull requests by Patrick (#363 and #364) - is there a reason for this?

The changes you've made in [frmUserManagement.vb](https://github.com/opencdms/Climsoft/pull/365/files#diff-b298fc39edfb82dbc060ca8b87e4f4a0) appear to be new, but in many places code like...

```
Sql = "GRANT SELECT ON " & dbnme & "   ...
```

has now changed to 

```
Sql = "GRANT SELECT ON mariadb_climsoft_test_db_v4   ...
```

The name of the test database has been hardcoded instead of using the `dbname`.  Doesn't this mean that the code will now only work with the test database and not the database that the user has selected?

**Comment by mhabimana** [comment]
@smachua  As @isedwards is recommending,is it possible to send through 2 separates PRs, one to delete the redundant folder 'ClimsoftVer4_31082018' and another one to update the user management feature?

**Comment by isedwards** [comment]
I wouldn't worry too much about separating this into two pull requests now, but it would be good to get your thoughts on the other two questions.

**Comment by smachua** [comment]
@isedwards the redundant folder need to be deleted whichever method otherwise it will keep reappearing whenever cloning is done.

Following is the response to the other 2 questions by @isedwards :
Since both databases have similar tables the permission has to be simultaneously granted to both similar tables. Hence there is code for each database. The test database name should be the same but the operational one can vary. The problem was with only few tables in test database. It had escaped all the previous tests mainly because users have been connecting to the test database only as root.

**Comment by mhabimana** [comment]
@smachua I think we are missing one point, the reason why the changes done by @Patowhiz is reappearing again in this PR

**Comment by smachua** [comment]
@mhabimana and @isedwards I have no explanation as to why some changes are similar in both #363 and #364 unless the merging was not successfully completed in the earlier PR.

**Comment by isedwards** [comment]
Great - this is good progress.  I will take a look to understand why Patrick's changes are showing up again (this is unusual and we want to make sure that nothing is going wrong here).

Then we can modify this PR so that it no longer has the changes from Patrick that are already merged (and also, since the PR is being modified we can also separate out the the deletion of the 565 backup files so that this is also not part of the PR).

This should leave a very clean pull request with only the actual changes being made to the code (it looks like these changes are to a single file: `frmUserManagement.vb`). We can then review/discuss and merge this more easily.

**Comment by mhabimana** [comment]
Sounds great.

**Comment by isedwards** [comment]
@smachua can you describe how you are getting the recent changes that other people have made into your copy of the code? Do you do something in GitHub Desktop or do you manually copy and paste the files that have recently changed?

**Comment by smachua** [comment]
@isedwards I synchronize my branch with master.

**Comment by mhabimana** [comment]
@isedwards; Thanks,let me test this.

**Comment by mhabimana** [comment]
@smachua I am still not able to login after merging.users with the  roles **root** and **admin** are able to login into the test and operation  database at the same time. others not yet(see (1)below). @isedwards  what about the cahnges to **M ClimsoftVer4/ClimsoftVer4/frmMonitoring.vb (1)**,was this empty I was expecting this to solve the issue (2) below:
1.
image


2.
image

**Comment by isedwards** [comment]
Samuel's pull requests are showing all of the changes that exist on his branch - these include changes that other people have recently made that have been added to the branch by synchronising using GitHub Desktop.  The synchronised changes appear in the PR as if Samuel had authored them and therefore it is currently giving the impression that he is editting more of the data entry files than he actually is.  These extra changes also make the PRs harder to review (because it's not clear which changes are actually his) but now that I can see what is happening it will be easier going forward.

In the future we can avoid this by using `git rebase` and not merging or synchronising to keep a branch up-to-date, but for now it is not a huge problem and it is probably easiest to continue as we are until we can update our processes.

We can compare the original pull request (#365) with the "merge commit" ([a944232](https://github.com/opencdms/Climsoft/commit/a94423211e208411b9b7262a336f292212b7e6c4)) that was generated when the pull request was approved an merged.  The merge commit shows the files in master that were actually modified when the PR was merged.

Merge commits are created when there are two parents in the history (i.e. you have made local changes and the upstream master also has changes not included in your local branch).  Rebasing removes the second parent and therefore removes the need for an additional merge commits.

**Comment by smachua** [comment]
@mhabimana permissions are granted when a user is being created. Ignore the users you had created before the bug was fixed. However, somehow changes for granting permissions to some tables for user types; ClimsoftOperator and ClimsoftRainfall seems to have been lost. The rest are ok. I will make another PR to fix that.

**Comment by mhabimana** [comment]
@smachua :Thanks and noted.Let me try this.

**Pull request merged**
