### PR TITLE
Upload Functions For All Data Entry Forms

### PR DESCRIPTION
**Pull request by Patowhiz**
@maxwellfundi  @smachua  @mhabimana  This fixes upload for all the data entry forms using the usual sql commands. I have left the code for upload through the EF.
Please note I'm yet to implement the waiting dialog and the progress bar, but the actual upload code is done.

### CODE REVIEW

**Comment by isedwards** [comment]
Very good to see the use of parameterised queries. This moves us towards solving #194

**Comment by Patowhiz** [comment]
Yeah. In future we can have much more strict parameterized queries once the database becomes stable. I was keen not to have this now because of how we are still changing tables columns properties

**Comment by mhabimana** [comment]
@Patowhiz The upload is working well but the form synop_2_ra1 is still having issues. I am sure is you have finalise this.

**Comment by Patowhiz** [comment]
FormSynoptic issues is dependent on the EF and the Database. I have outlined the issues to Samuel and Ian. There are columns missing for certain elements

**Comment by mhabimana** [comment]
@Patowhiz Sorry,the issue was on my side.otherwise Ian has updated EF. So,forgot to update my data base with the attached script. Now I am ok.

**Pull request merged**
