### PR TITLE
Data Entry Forms (with conflicts resolved)

### PR DESCRIPTION
**Pull request by isedwards**
Fixes conflicts in #551
Please test before merging.

### CODE REVIEW

**Comment by maxwellfundi** [comment]
@isedwards Am on it!

**Comment by maxwellfundi** [comment]
@mhabimana @iedwards @smachua  I have looked at these changes and they pretty much whats needed. Its okay to be merged. 

Just one simple thing that we will need to improve on the forms is when- a value thats beyond the or below the limits is entered, the enter should keep going but the cell remains cyan.. 

otherwise this is all good.

**Comment by isedwards** [comment]
All of the commits that were on the Climsoft `dev` branch have now been merged.  Since there is nothing else left on this branch I've deleted it for now.

**Comment by Patowhiz** [comment]
@maxwellfundi we can now start addressing those individual bugs in specific PR. I'll open an issue on the same

**Pull request merged**
