### PR TITLE
Improvement on Data Inventory

### PR DESCRIPTION
**Pull request by vralenkoane**
Created 2 DB stored procedures
1. One to truncate missing data from table
2. Two to find from table observationfinal values that are null for a given station over a given element at a specified time. the missing is denoted as xx.x and is outputed to .csv file.

### CODE REVIEW

**Comment by mhabimana** [comment]
@vralenkoane -Thanks for the work,please send through the scripts as well

**Comment by mhabimana** [comment]
[Background_Inventory.Scripts.txt](https://github.com/opencdms/Climsoft/files/1294838/Background_Inventory.Scripts.txt)
The attached script is associated with the above branch and should be run to create a table in the database.

**Comment by mhabimana** [comment]
@vralenkoane - I am getting errors while trying to load the script into the database(see below):tables are not being created. Can you please revise this?
image

**Comment by mhabimana** [comment]
@vralenkoane - Here is the test feedback.
1.inventory using victor's work:I took some time(minutes) to extract the inventory output file for daily rainfall data for one station as per attached files compared to the inventory output from  Samuel's work though the content differ a bit since ;Victor's work is detecting and output the null values in the define period but Samuel's the missing values. 
Attached is the data(product output) and the inventory outputs using both samuel' and victor's work for your review:

1. [inventory-products_Victor.txt](https://github.com/opencdms/Climsoft/files/1298605/inventory-products_Victor.txt);
2. [inventory-products_Samuel.txt](https://github.com/opencdms/Climsoft/files/1298618/inventory-products_Samuel.txt);
3. [data_products.txt](https://github.com/opencdms/Climsoft/files/1298619/data_products.txt)
Further discussion is needed on this.

**Comment by vralenkoane** [comment]
The refresh_data script, deletes and re-create the table missing data. This is meant to optimize the query.
missing_data( script takes stationid, elementid,startdate,enddate as its parameters. then it will go through the observationfinal table in the db and search for records that match stationid,elementid and their observation date is between startdate and enddate. any instance where no value is found in the search is logged into missing_data table. once the done the application reads the contents of missing_data into csv file which is opened by excel.

**Comment by mhabimana** [comment]
@vralenkoane - Thanks victor, Yes,It is working the way you explained above.However,my question to you is when the refresh script take effect? is it during the creation of the inventory product output?(here I mean when clicking on extract button?) please let us know.

**Comment by vralenkoane** [comment]
that is meant to ensure that there no duplicates in the missing. The refresh script runs before calling the missing_data script and truncates the missing_data table. this is to ensure that no duplicates in the data

**Comment by mhabimana** [comment]
@vralenkoane - I am asking as a user,I imagine all this process is taking place behind the scene and the user will just produce the inventory product.Is this true or not?

**Pull request closed without merging**
