### PR TITLE
EF Model update (remove new pks)

### PR DESCRIPTION
**Pull request by isedwards**
The database has been reverted to remove the new primary keys - this PR updates the Entity Framework model to correspond to this update to he database.

_This PR is not currently ready to merge_. There are build errors in `ucrMonthlyData.vb` relating to `form_monthly` (which has now disappeared from the model). We also expect there to be problems with uploading to `observationinitial`.

### CODE REVIEW

**Comment by maxwellfundi** [comment]
@isedwards  I have tested this and confirm that form Monthly is missing out on the model and the upload of course does not work. @smachua we are now trying to incorporate your upload functions to see that works well to upload. I also would like to understand from @smachua  and @mhabimana , whats the implication of not  having this monthly form? @isedwards would there be an easy way from your side to include this form?

**Comment by mhabimana** [comment]
@maxwellfundi Thanks,This form is very important to key in monthly data (12 values per year) into climsoft.It used to work well in previous versions of climsoft.

**Comment by maxwellfundi** [comment]
Thank you @mhabimana  for your response, I think we need to soonest find a solution to this

**Comment by isedwards** [comment]
`form_hourly` is visible because this table has a primary key (in this case it's a composite primary key).

`form_monthly` is missing because the table doesn't have any primary key defined (it has a composite index, but this has not been set as the primary key)

**Comment by mhabimana** [comment]
@isedwards I think if the PK is needed for this form to work,this should be added,because other forms have got the PK. I think the issues was to add the id to major tables and not on data entry forms. May be @smachua can clarify on this.

**Comment by maxwellfundi** [comment]
Thank you @isedwards . @smachua what is the reason for having these fields(stationId ,elementId,yyyy) as a composite key and not primary key for this table. I understand that the form should have only 12 values for the elements for every year. 
I think we can have these fields as PK?

**Comment by smachua** [comment]
@maxwellfundi and @mhabimana the composite key (stationId ,elementId,yyyy) can be made Primary key. It's only that the modules we have been using only required a unique key whatever name given. I have modified the table to have a primary key and attached the script. However, there will not be much harm if form_monthly is left out. Let it not hold you down if it's difficult to implement.
[form_monthly.txt](https://github.com/opencdms/Climsoft/files/2245869/form_monthly.txt)

**Comment by Patowhiz** [comment]
@isedwards can we have the form_monthly primary key back, since it's now added by samuel

**Comment by isedwards** [comment]
Below are the same changes that @smachua provided, but as an `ALTER` statement.  You can use this if you already have data in `form_monthly` that you would like to keep (instead of dropping and recreating the table).  The `CHANGE COLUMN` commands are adjusting the columns so that they will no longer accept `NULL` values.

```
ALTER TABLE `form_monthly`
	CHANGE COLUMN `stationId` `stationId` VARCHAR(255) NOT NULL DEFAULT NULL FIRST,
	CHANGE COLUMN `elementId` `elementId` INT(11) NOT NULL DEFAULT NULL AFTER `stationId`,
	CHANGE COLUMN `yyyy` `yyyy` INT(11) NOT NULL DEFAULT NULL AFTER `elementId`,
	DROP INDEX `identification`,
	ADD PRIMARY KEY (`stationId`, `elementId`, `yyyy`);
```

**Comment by isedwards** [comment]
I've further updated the model, `form_monthly` is now available again. There are no build errors so this PR could be merged or we could wait until the new update code is also added.

**Comment by maxwellfundi** [comment]
@isedwards  I suggest that @smachua  merges this now the other bits could keep going in.

**Comment by Patowhiz** [comment]
@smachua @isedwards @maxwellfundi @mhabimana as you fix the EF model for frmMonthly also check on form synoptic to work, we need the columns **Flag169, Flag170, Flag171** both in the database and the EF model . Their corresponding Val_Elem169, Val_Elem170, Val_Elem171 are already there.

**Comment by mhabimana** [comment]
sounds great

**Pull request merged**
