### PR TITLE
Set default database if none exists

### PR DESCRIPTION
**Pull request by isedwards**
If no databases have been specified in `\ProgramData\Climsoft4\config.inf` (or the file has not yet been created) then the default database is shown.

The connection string for the default database is from `My.Settings.defaultDatabase`

### CODE REVIEW

**Comment by isedwards** [comment]
@mhabimana, if you cannot see the default database when using this verion then the most likely reason is that you already have a `\ProgramData\Climsoft4\config.inf` file that is left over from testing an earlier version of the code.

If this file exists then then the contents of the file will be used (even if the file is empty).  If you delete the file you should see the default database.

**Comment by mhabimana** [comment]
@isedwards -You are right.I had to delete the  config.inf file in this path and run start again Climsoft in VS and here is the login dialog with the default database:
image

**Comment by mhabimana** [comment]
@isedwards - I am not able to add a new database connection.Here is the error message I am getting:
image

**Comment by isedwards** [comment]
It looks like I've not allowed spaces. I'll change it so that spaces are okay.

In the meantime you'll have to change the connection name to Default_database with an underscore.

**Comment by mhabimana** [comment]
@isedwards - Thanks, yes,it is working well with the default but wanted to check if I can add manually the test and other databases located on the remote computer (server).

**Comment by mhabimana** [comment]
@isedwards - After changing form Default database to **Default_database**, I am now able to add a new connection
image

**Pull request merged**
