### PR TITLE
Comboboxes Default Values

### LINKED ISSUE #417: Form Daily2 Default observation Hour set at 6
@Patowhiz: Just to suggest a small change on the Form Daily2 data entry form. Currently, the default hour of observation on this form is set to **0** ,this happen when opening an empty Daily2 form. My suggestion is to set this at **6** instead of **0** because in many National Met Services,the Daily Data are confirmed at **06:00 UTC**. In this case,**6** should displays under the Hour when opening this form.I am available for more details if required.
image

### PR DESCRIPTION
**Pull request by Patowhiz**
Fixes #417 
@opencdms/climsoft-developers this is ready for review.
@dannyparsons please review this before @mhabimana merges it. The code changes affect the parent controls.

### CODE REVIEW

**Comment by mhabimana** [comment]
@Patowhiz @isedwards : I wanted to test this separately before the merging into Master but I can not see the branch containing this. Any help?

**Comment by isedwards** [comment]
If you have the GitHub extension installed in Visual Studio then you should be able to sign into GitHub using the GitHub tab that is next to Solution Explorer and Team Explorer in Visual Studio.  If you do this, do you then see Patrick's branch (which was created in his personal GitHub account)?

**Comment by mhabimana** [comment]
@isedwards :Thanks,I get your point.Let me try this

**Comment by mhabimana** [comment]
@isedwards : I can see the checkout link is not active(see below):
image

**Comment by mhabimana** [comment]
@isedwards : I am unable to checkout this PR because my directory has uncommitted changes see the screenshot above. How should I go about this?

**Comment by dannyparsons** [comment]
@mhabimana you either need to commit the changes to those four file or undo the changes to be able to checkout another branch.

If the changes are part of some work you are doing, to keep them go to Team Explorer home, click Changes and enter a message to Commit it to your branch.

If you don't need to keep the changes then you can right click on the four files and select "Undo Changes..." (to see what the changes are first right click and select "Compare with Unmodified...")

**Comment by mhabimana** [comment]
@dannyparsons : Thanks,I am now OK.

**Comment by mhabimana** [comment]
@dannyparsons @isedwards I am managed to checkout this PR and I can see the default Hour(HH) of observation was fixed well as suggested on both Form_Daily and Synop_2_ra1. This can be merged now.

**Pull request merged**
