### PR TITLE
EntryDateTime Update & formMonthly Sequencer

### LINKED ISSUE #371: Entry Date and Time Field required in New Data Forms
This Field is required in all the new Data Entry form created by AMI,this will enable the computation of  records entered by a particular user (very helpful in data monitoring). @smachua has got already  a line of code to do this task and it exists already in form agro1. 
image

image

### LINKED ISSUE #374: Sequencer Table for the Monthly Data Entry Form.
The AddNew button on this form is not working the way it should because the sequencer table of this form is missing. This is very needed.

### PR DESCRIPTION
**Pull request by Patowhiz**
Fixes #371
Fixes #374

@mhabimana @smachua I'm yet to test this because I lack the new database with values. I only have the empty one that has no testable key entries.

### CODE REVIEW

**Comment by mhabimana** [comment]
@Patowhiz Thanks,@smachua can please share this script ?

**Comment by smachua** [comment]
@Patowhiz and @mhabimana. I attached the test database script.

[climsoft_database_test.zip](https://github.com/opencdms/Climsoft/files/2396867/climsoft_database_test.zip)

**Comment by Patowhiz** [comment]
@smachua thanks. To clarify, the `entryDateTime ` is only updated for new records(I'm still not sure why) and it's value is not uploaded to observationinitial table, and the formMonthly will now have its sequencer set as `seq_monthly_element`. On the other hand, @smachua @mhabimana in what order should the records be loaded in the forms, should we use the `entryDateTime `column to order in ascending?

**Comment by Patowhiz** [comment]
@mhabimana this is now ready for review.

**Comment by mhabimana** [comment]
@Patowhiz  Thanks @smachua Kindly review this and clarify on @Patowhiz message above.

**Comment by smachua** [comment]
@Patowhiz yes entryDatetime and signature fields are only updated in new entries. Values for signature are uploaded into the field capturedBy in the observationinitial but entryDatetime values remain in the forms.

The order of loading the data doesn't matter. The modules that use them sort by the relevant fields.

**Comment by isedwards** [comment]
@Patowhiz - go you know why you sometimes have extra merge commits in your pull requests?

This time you had [3 commits](https://github.com/opencdms/Climsoft/pull/383/commits), the first two commits merge in old PRs that have already been merged long ago (so there is no impact on the code) and the final commit contains the changes that you are actually making.

**Comment by mhabimana** [comment]
@smachua  Can you please find out why I am getting this issue of permission on this table(see below)
image

**Comment by smachua** [comment]
@mhabimana I am going to address it immediately. You may try other forms also.

**Comment by mhabimana** [comment]
@smachua Noted.

**Comment by Patowhiz** [comment]
@iedwards the extra 2 commits have been "incremented" by github when I merged  changes from opencdms to my branches. They have no changes though.

> @Patowhiz - do you know why you sometimes have extra merge commits in your pull requests?
> 
> This time you had [3 commits](https://github.com/opencdms/Climsoft/pull/383/commits), the first two commits merged again old PRs that have already been merged long ago (so there is no impact on the code) and the final commit contains the changes that you are actually making.

**Pull request merged**
