### PR TITLE
Update to Entity Framework model

### PR DESCRIPTION
**Pull request by isedwards**
The PR adds the new `EntryDatetime` field to key entry tables and removes `Flag178`, `Flag179` and `Flag180` from `form_synoptic2_ra1`.

Note that, in the database, the new database field is named `EntryDatetime` in `form_daily2` and `form_hourly` whilst it is named `entryDatetime` in `form_hourlywind`, `form_monthly` and `form_synoptic2_tdcf`.

(The stored procedures have been removed from the Entity Framework model since we currently do not access them from the model and do not need to keep them up-to-date here).

### CODE REVIEW

**Comment by smachua** [comment]
@isedwards I am not sure why you have indicated that the new field is named entityDatetime and not entryDatetime. Is it a typing error? Please clarify. In the code it is used as entryDatetime.

**Comment by isedwards** [comment]
Thanks Samuel -that is a mistake/typo!  I've now corrected it above.

**Comment by mhabimana** [comment]
@smachua Are you happy to merge this now?

**Comment by Patowhiz** [comment]
@isedwards I hope you added the sequencer table that @mhabimana wants us to use in formMonthly

**Comment by isedwards** [comment]
@Patowhiz - yes, the new sequencer table is here [seq_monthly_element.vb](https://github.com/opencdms/Climsoft/pull/381/files#diff-898644e8c8f7d164e01ee8ed37f99a78)

**Pull request merged**
